[package]
name = "ruok"
version = "0.1.0"
authors = ["Olly Swanson"]
description = "Reserved for an idea"
license = "MIT"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
